# Generated by Django 5.0 on 2023-12-06 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Choose your unique username of 4 to 16 characters.",
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=0,
                        message="Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.",
                        regex="^[\\w.@+-]+\\Z",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="Username must be at least 4 characters long.",
                    ),
                ],
                verbose_name="username",
            ),
        ),
    ]
