# Generated by Django 5.0.4 on 2024-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_capitals_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='languages_highscore',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
