# Generated by Django 5.1 on 2024-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekentry',
            name='exercise_link',
            field=models.URLField(blank=True, default='#', help_text='Link to the exercise for the week.', verbose_name='Link to the exercise'),
        ),
        migrations.AlterField(
            model_name='weekentry',
            name='exercise_materials_link',
            field=models.URLField(blank=True, default='#', help_text='Link to the exercise materials for the week.', verbose_name='Link to the exercise materials'),
        ),
        migrations.AlterField(
            model_name='weekentry',
            name='solutions_link',
            field=models.URLField(blank=True, default='#', help_text='Link to the solutions for the week.', verbose_name='Link to the solutions'),
        ),
    ]
