# Generated by Django 5.1.1 on 2024-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_weekentry_exercise_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekentry",
            name="materials_number",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The materials number for this entry.",
                verbose_name="Materials Number",
            ),
            preserve_default=False,
        ),
    ]
