# Generated by Django 5.2.4 on 2025-08-12 17:27

from django.db import migrations


def create_hs25_session(apps, schema_editor):
    ExerciseSession = apps.get_model("main", "ExerciseSession")

    # Create HS25 session
    hs25_session, created = ExerciseSession.objects.get_or_create(
        short_name="TM_HS25", defaults={"name": "Engineering Mechanics HS2025"}
    )

    if created:
        print(f"Created new exercise session: {hs25_session}")


def reverse_create_hs25_session(apps, schema_editor):
    ExerciseSession = apps.get_model("main", "ExerciseSession")

    # Delete HS25 session if it exists
    try:
        hs25_session = ExerciseSession.objects.get(short_name="TM_HS25")
        hs25_session.delete()
        print("Deleted HS25 exercise session")
    except ExerciseSession.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_weekentry_exercise_link_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_hs25_session,
            reverse_create_hs25_session,
        ),
    ]
