"""
Django settings for nethz_django project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

Reverse proxy (Traefik) notes:
- We trust `X-Forwarded-Proto: https` so `request.is_secure()` works.
- We trust forwarded host so `request.get_host()` matches the public hostname.
This is important for SEO endpoints like `robots.txt`/`sitemap.xml` to emit correct
absolute URLs.
"""

from pathlib import Path

from decouple import config
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

APPEND_SLASH = False

ENVIRONMENT = config("ENVIRONMENT", default="production", cast=str)
PRODUCTION_DOMAINS = config("PRODUCTION_DOMAINS", default=None)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    cast=str,
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Set to True only in development environment

ALLOWED_HOSTS = []

if ENVIRONMENT == "development":
    DEBUG = True
    ALLOWED_HOSTS.append("*")
    MESSAGE_LEVEL = messages.DEBUG
    CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]

if ENVIRONMENT == "testing":
    DEBUG = False
    ALLOWED_HOSTS.append("*")
    CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]

if ENVIRONMENT == "production":
    DEBUG = False

    if PRODUCTION_DOMAINS:
        # To avoid adding empty strings to allowed hosts
        ALLOWED_HOSTS.extend(
            domain.strip() for domain in PRODUCTION_DOMAINS.split(",") if domain.strip()
        )

        # Add CSRF trusted origins for HTTPS
        CSRF_TRUSTED_ORIGINS = [
            f"https://{domain.strip()}"
            for domain in PRODUCTION_DOMAINS.split(",")
            if domain.strip()
        ]

    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "PRODUCTION_DOMAINS must be set in production environment OR"
            "update ALLOWED_HOST in the projects settings.py"
        )

    # --- Reverse proxy / Traefik ---
    # Ensure Django recognizes the original scheme and host from Traefik.
    # Traefik sets `X-Forwarded-Proto: https` for TLS-terminated requests.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # If Traefik forwards the Host header, this makes `request.get_host()` use it.
    # This is needed so robots.txt can emit a correct absolute sitemap URL.
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    "jazzmin",  # Must be before django.contrib.admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "crispy_forms",
    "crispy_bootstrap5",
    "accounts.apps.AccountsConfig",
    "lib",
    "main.apps.MainConfig",
    "worldle.apps.WorldleConfig",
]


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # SEO: 301 redirects for root URL and trailing slashes (needs session first)
    "nethz_django.middleware.SEORedirectMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "nethz_django.middleware.EmailVerificationMiddleware",
    # Workaround: Remove X-Robots-Tag: noindex set by Traefik/Pangolin proxy
    "nethz_django.middleware.RemoveNoindexHeaderMiddleware",
]

ROOT_URLCONF = "nethz_django.urls"

# Caching - Simple in-memory cache for template fragments
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,  # Do not disable, needed for crispyforms!
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "lib.context_processors.inject_global_context",
            ],
        },
    },
]

WSGI_APPLICATION = "nethz_django.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db" / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.CustomUser"


LOGIN_URL = "accounts:login"
LOGOUT_URL = "accounts:logout"

LOGIN_REDIRECT_URL = "worldle:home"
LOGOUT_REDIRECT_URL = "main:home"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "de"
USE_I18N = True
LANGUAGES = [
    ("en", "English (US)"),
    ("de", "German (CH)"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]


USE_TZ = True
TIME_ZONE = config("TZ", default="UTC", cast=str)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]


if ENVIRONMENT == "production" or ENVIRONMENT == "testing":
    STATIC_URL = "assets/"
    STATIC_ROOT = (
        BASE_DIR / "assets"
    )  # python manage.py collectstatic saves files there
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    
    # WhiteNoise optimization - Better caching and compression
    WHITENOISE_MAX_AGE = 31536000  # 1 year for immutable files
    WHITENOISE_USE_FINDERS = False  # Disable in production (files already collected)
    WHITENOISE_AUTOREFRESH = False  # Disable auto-refresh in production


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ENVIRONMENT = config("ENVIRONMENT", default="production", cast=str)
# PRODUCTION_DOMAINS = config("PRODUCTION_DOMAINS", default=None)


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default=None)
EMAIL_PORT = config("EMAIL_PORT", default=None, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default=None)
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default=None)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST)

if any(
    [
        not EMAIL_HOST,
        not EMAIL_PORT,
        not EMAIL_HOST_USER,
        not EMAIL_HOST_PASSWORD,
        # not DEFAULT_FROM_EMAIL,
    ]
):
    raise ImproperlyConfigured(
        "Email not properly configured!\n\n"
        "EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL must be set in the environment."
    )


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "nethz_django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

if DEBUG:
    LOGGING["loggers"]["django.request"]["level"] = "INFO"

# Django Jazzmin (Modern Admin Panel) Configuration
JAZZMIN_SETTINGS = {
    # Title on the login screen (19 chars max)
    "site_title": "nETHz Admin",
    # Title on the brand (19 chars max)
    "site_header": "nETHz",
    # Title on the brand when user is logged in (19 chars max)
    "site_brand": "nETHz Admin",
    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": None,
    # Logo to use for login form, must be present in static files
    "login_logo": None,
    # Logo to use for login form in dark themes
    "login_logo_dark": None,
    # CSS classes that are applied to the logo above
    "site_logo_classes": None,
    # Relative path to a favicon for your site, will default to site_logo if absent
    "site_icon": None,
    # Welcome text on the login screen
    "welcome_sign": "Welcome to nETHz Admin Panel",
    # Copyright on the footer
    "copyright": "Enzo Baraldi",
    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": None,
    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # external url that opens in a new window (Permissions can be added)
        {"name": "Website", "url": "/", "new_window": True},
    ],
    #############
    # User Menu #
    #############
    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Website", "url": "/", "new_window": True},
    ],
    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],
    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],
    # List of apps (and/or models) to base side menu ordering off of
    "order_with_respect_to": ["auth", "accounts"],
    # Custom links to append to app groups, keyed on app name
    "custom_links": {},
    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts.CustomUser": "fas fa-user-circle",
        "main.ExerciseSession": "fas fa-book",
        "main.WeekEntry": "fas fa-calendar-week",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    # Add a language dropdown into the admin
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}
