name: Format code

on:
    push:
        branches: ["master"]
    workflow_dispatch:

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.x"

            - name: Format code with ruff
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff
                  ruff .

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Auto-format code with Ruff"

            # - name: Commit formatted code
            #   run: |
            #       git config --local user.email "action@github.com"
            #       git config --local user.name "GitHub Action"
            #       git add .
            #       git commit -m "Auto-format code with Ruff" || true
            #       git push

            #   - name: Commit changes
            #     uses: EndBug/add-and-commit@v4
            #     with:
            #         author_name: ${{ github.actor }}
            #         author_email: ${{ github.actor }}@users.noreply.github.com
            #         message: "Format code with ruff"
            #         add: "."
            #         branch: ${{ github.ref }}
